# Generated by Django 4.1 on 2023-07-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("semantic", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="News",
        ),
    ]
