# Generated by Django 4.1 on 2023-07-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpusentry",
            name="index",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
