# Generated by Django 4.1 on 2023-07-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_corpusentry_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corpusentry",
            name="index",
        ),
    ]
