# Generated by Django 4.1 on 2023-07-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_remove_corpusentry_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpusentry",
            name="embedding",
            field=models.BinaryField(),
        ),
    ]
