# Generated by Django 4.1 on 2023-07-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0004_alter_corpusentry_embedding"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CorpusEntry",
        ),
    ]
