# Generated by Django 4.1 on 2023-07-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("search", "0005_delete_corpusentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorpusEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("embedding", models.BinaryField()),
            ],
        ),
    ]
