# Generated by Django 4.1 on 2023-07-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0007_remove_corpusentry_embedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corpusentry",
            name="id",
        ),
        migrations.AddField(
            model_name="corpusentry",
            name="index",
            field=models.IntegerField(
                default=1, primary_key=True, serialize=False, unique=True
            ),
            preserve_default=False,
        ),
    ]
